### ISSUE TITLE
inbound/odfi: path matcher for each processor

### ISSUE THREAD

**Issue by zbruhnke** [moov-io/achgateway#112]
While achgateway currently supports Filename templating for `OUTGOING` files it does not support them for `INCOMING` files, this can lead to a situation where an ODFI has a lack of capabilities to drop files of different types into multiple folders in an SFTP but instead wants to break this up by giving Filenames.

For example rather than using a folder structure like 

`/incoming/ach-file-name` 

an ODFI might use a filename structure like

`INCOMING_ACH_FILE_file-name`

or

`RETURN_ACH_FILE-file-name`

However in the current integration this is not supported very well unless we just process all files as one type or we have our ODFI generate unique credentials for each type of file generated which is also a pain.

In an ideal world we'd be able to sort incoming files by either filename structure, folder structure or even both. This would provide the maximum level of configurability

**Comment by adamdecaf** [comment]
Yea this should be easy enough. We have `PathMatcher` on the [Reconciliation](https://moov-io.github.io/achgateway/config/#inbound) processor, so the same could apply.
