### ISSUE TITLE
No Healthcheck endpoint

### ISSUE THREAD

**Issue by zbruhnke** [moov-io/achgateway#118]
Most of the other Moov services have the `/ping` endpoint as a convenient built in healthcheck. I just happened across it that this is not the case in achgateway when building a paw/postman collection for it. This feels like something that should likely be added for those that rely on these endpoints

**Comment by adamdecaf** [comment]
Releasing [v0.16.0-rc5](https://github.com/moov-io/achgateway/tree/v0.16.0-rc5) with this. I'm planning this to be the last release candidate.
