### ISSUE TITLE
Populate incoming file with hash of contents as ID 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/achgateway#125]

**Comment by yordis** [comment]
Hey there, just to make sure I understood correctly

```elixir
 %{
      file_header: nacha_file.fileHeader,
      batch_header: batch.batchHeader,
      # NOTE: Why are we adding an ID to the entry detail?
      #  Because the ACH Gateway is not putting IDs. This will no longer be needed after https://github.com/moov-io/achgateway/issues/125
      #  is fixed.
      entry_detail: Map.put(entry_detail, :id, @id.new())
    }
```

Does that mean I can eliminate my comment about creating a `UUID` for the entry details once this is closed?

**Comment by adamdecaf** [comment]
What endpoint are you calling? This issue was more about retrieving files from the ODFI.

**Comment by yordis** [comment]
I am not calling any endpoint, just processing the achgateway message that didn't add the UUIDs to the incoming file.

It is related to https://github.com/moov-io/ach/pull/1063#discussion_r938302602

We lost a lot of the IDs right now from the events coming out of `achgateway` Kafka message so I need some of them such as the `entryDetails.id` one

**Comment by adamdecaf** [comment]
I didn't realize the `id` field was an expected field on those messages. It's not a required field so it can be blank. This issue is talking about specifying the File's ID as a hash of the contents, but I wasn't planning to populate `id` on EntryDetail records.

**Comment by yordis** [comment]
Ahhh got it! Well, I take that one as well!
