### ISSUE TITLE
proposal: remove consul support / leadership elections

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/achgateway#174]
At Moov we've stopped running achgateway with consul support and [others have deployed without consul](https://moov-io.slack.com/archives/CD9J8EJKX/p1683679107764729?thread_ts=1683645647.517489&cid=CD9J8EJKX) as well. The consul implementation has several known issues and does not work as expected. 

- File consistency across instances is not guaranteed with consul. Instances can isolate/upload different sets of ACH files.
- Files are not stored in consul which is often assumed to be the case. 
- Users can be confused to share one Persistent Volume or have unique volumes per instance.

**Comment by jrnt30** [comment]
We are not currently using it either.  We had initially but ran into a few of those issues outlined above and ended up removing it from our infrastructure. In the current state, I do feel like it could potentially lead to data loss/unexpected file processing semantics if folks are moving quickly. 

Personally supportive of deprecating/removing Consul for the time being and either leaning into it and using it as the distributed file store as well or looking to a different HA solution all together.
