### ISSUE TITLE
feat: support Google Cloud Spanner as an additional repository

### ISSUE THREAD

**Issue by kevinbarbour** [moov-io/achgateway#214]
Due to a business requirement that all of our financial stack is backed by multi-region databases we will need to run the achgateway with a Spanner database instead of MySQL. 

I am actively working on adding this feature in a fork of the achgateway right now and will submit a PR for this capability if it's something that would be accepted as a feature for the product.

**Comment by adamdecaf** [comment]
Yea that's fine. We use spanner internally at Moov so it's welcome in OSS.

**Comment by kevinbarbour** [comment]
done in #220
