### ISSUE TITLE
bug: multiple ACH files with the same routing number will overwrite eachother at cutoff time

### ISSUE THREAD

**Issue by kevinbarbour** [moov-io/achgateway#215]
When multiple ACH files are queued to go out at cutoff time, and have the same routing number, only the last one is actually persisted at the ODFI because any files uploaded in the same second have the same filename.

To reproduce:

- Submit two ACH files to the ACH Gateway with the same shard key, each with the same routing number in the file header.
- Manually trigger a cutoff for the given file
- ACH Gateway uploads a file for the first one named `20231215-1439400-123456789.ach`
- ACH gateway uploads a file for the second one, within the same 1 second period, and also names it `20231215-1439400-123456789.ach`, overwriting the first file

The usage of the template `YYYYMMDD-HHMMSS-ROUTINGNUMBER.ach` for these filenames is what is causing this. I can submit a PR to fix this, but am curious about the intent behind this design and what would be the preferred fix. Was the assumption that the gateway would always be configured to merge all files going to the same routing number before upload?

It looks like filenames used to contain a more precise timestamp, but were changed to only name files down to the second:

https://github.com/moov-io/achgateway/commit/09f77ee7a3cb9b59332df0da0f93ea2916bd4695

Alternatively a UUID or unique File ID could be added to this name to make sure file names do not overlap.

**Comment by adamdecaf** [comment]
What we use is [`{{ .Index }}`](https://github.com/moov-io/achgateway/blob/v0.27.2/internal/upload/filename_template_test.go#L80-L87) which refers to the ith file after merging. We haven't ran into an FI that prevents us from including this in the filenames. There's an `env` template function and more precise / specific timestamps can be provided as well.

**Comment by kevinbarbour** [comment]
Thanks for the quick response, that is perfect.

Do you think it's worthwhile to add that to the default template so that out of the box behavior doesn't lead to overwriting files? Otherwise I will just close this.

**Comment by adamdecaf** [comment]
Yea that sounds like a good thing to fix. It's unexpected that files would be overwritten by default.
